// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duqnojkhcuodqnpcqeay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1cW5vamtoY3VvZHFucGNxZWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MDQyOTQsImV4cCI6MjA3MTQ4MDI5NH0.0vg8hyETyEwINgPDyzDTmQCOPrqxEt4lb0WHJB4sAC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});